version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass1212
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/sql/create_db.sql:/docker-entrypoint-initdb.d/01_create_db.sql
      - ./src/sql/fill_db.sql:/docker-entrypoint-initdb.d/02_fill_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=inventory
      - DB_USER=admin
      - DB_PASSWORD=adminpass1212
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

volumes:
  postgres_data: